### ISSUE TITLE
Resources validation tool

### ISSUE THREAD

**Issue by spilio** [spilio/openreferral-playground#1]
Tool that will aid users in learning about different Open Referral resource schemas and validating sample CSV files against the latest version of the spec.

**Comment by xrysanthos** [comment]
## Screenshots
![image](https://user-images.githubusercontent.com/4200677/27260954-7d9897e2-5441-11e7-831e-81d5bdb0e245.png)

![image](https://user-images.githubusercontent.com/4200677/27260977-ea629ca6-5441-11e7-84a8-85feb093c640.png)

![image](https://user-images.githubusercontent.com/4200677/27260980-f028e4ec-5441-11e7-8175-24ba146db77b.png)

## Notes
Since the validator depends on the  Frictionless Data [tableschema-js](https://github.com/frictionlessdata/tableschema-js) library, it carries around its issues as well.  Notably the [following issue](https://github.com/frictionlessdata/tableschema-js/issues/70), which is scheduled to be included in v1.0.
